using Application.Common.Attributes;

namespace Application.Common.Enums
{
    public enum Permission
    {
        [StringValue("AddTopResource")]
        AddTopResource,
        [StringValue("UpdateTopResource")]
        UpdateTopResource,
        [StringValue("DeleteTopResource")]
        DeleteTopResource,
        [StringValue("ListTopResource")]
        ListTopResource,
        [StringValue("AddResource")]
        AddResource,
        [StringValue("UpdateResource")]
        UpdateResource,
        [StringValue("DeleteResource")]
        DeleteResource,
        [StringValue("ListResource")]
        ListResource,
        [StringValue("ListResourceArea")]
        ListResourceArea,
        [StringValue("AddResourceArea")]
        AddResourceArea,
        [StringValue("UpdateResourceArea")]
        UpdateResourceArea,
        [StringValue("DeleteResourceArea")]
        DeleteResourceArea,
        [StringValue("AddPermission")]
        AddPermission,
        [StringValue("UpdatePermission")]
        UpdatePermission,
        [StringValue("DeletePermission")]
        DeletePermission,
        [StringValue("ListPermission")]
        ListPermission,
        [StringValue("AssignPermission")]
        AssignPermission,
        [StringValue("AddRequiredDocument")]
        AddRequiredDocument,
        [StringValue("UpdateRequiredDocument")]
        UpdateRequiredDocument,
        [StringValue("DeleteRequiredDocument")]
        DeleteRequiredDocument,
        [StringValue("ListRequiredDocument")]
        ListRequiredDocument,
        [StringValue("AddProcess")]
        AddProcess,
        [StringValue("UpdateProcess")]
        UpdateProcess,
        [StringValue("DeleteProcess")]
        DeleteProcess,
        [StringValue("ListProcess")]
        ListProcess,
        [StringValue("AddProcessRequiredDocument")]
        AddProcessRequiredDocument,
        [StringValue("UpdateProcessRequiredDocument")]
        UpdateProcessRequiredDocument,
        [StringValue("DeleteProcessRequiredDocument")]
        DeleteProcessRequiredDocument,
        [StringValue("ListProcessRequiredDocument")]
        ListProcessRequiredDocument,
        [StringValue("ListChamberRegistration")]
        ListChamberRegistration,
        [StringValue("ApproveChamberRegistration")]
        ApproveChamberRegistration,
        [StringValue("ListOrganisationalUsers")]
        ListOrganisationalUsers,
        [StringValue("ViewOrganisationalUserDetails")]
        ViewOrganisationalUserDetails,
        [StringValue("AddOrganisationalUser")]
        AddOrganisationalUser,
        [StringValue("AddWorkflowScheme")]
        AddWorkflowScheme,
        [StringValue("ListApprovalInbox")]
        ListApprovalInbox,
        [StringValue("AddOrganisationApprovalRole")]
        AddOrganisationApprovalRole,
        [StringValue("ListOrganisationApprovalRole")]
        ListOrganisationApprovalRole,
        [StringValue("UpdateOrganisationApprovalRole")]
        UpdateOrganisationApprovalRole,
        [StringValue("ListOrganisationApprovalRole")]
        DeleteOrganisationApprovalRole



    }
}
